[package]
name = "wye_2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6"
rand = "0.8"
serde_json = "1.0.49"
serde_derive = "1.0.105"
serde = "1.0.105"